language: generic
dist: xenial

services:
  - mysql

before_install:
  - nvm use stable
  - gimme stable

install:
  - npm install
  - go get -d -t -v github.com/dxe/adb/...

before_script:
  - mysql -u root -e "CREATE USER adb_user@localhost IDENTIFIED BY 'adbpassword';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* to adb_user@localhost;"
  - mysql -u root -e "CREATE DATABASE adb_db CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -u root -e "CREATE DATABASE adb_test_db CHARACTER SET utf8 COLLATE utf8_general_ci;"

script:
  - npm run build
  - go build github.com/dxe/adb
  - go test github.com/dxe/adb/...
